import { ReliablePortal } from './types';

export const RELIABLE_PORTALS: ReliablePortal[] = [
  {
    id: 'scielo',
    name: 'SciELO Brasil (Ciências Agrárias)',
    shortName: 'SciELO',
    organization: 'FAPESP / CNPq / BIREME',
    description: 'Biblioteca científica eletrônica que abrange as principais revistas de agronomia do Brasil com acesso aberto e rigorosa revisão por pares.',
    focusArea: 'Ciência do Solo, Fitotecnia, Zootecnia, Engenharia Agrícola e Agroecologia',
    badge: 'Acesso Aberto & Qualis A',
    badgeColor: '#2E6F40',
    baseUrl: 'https://www.scielo.org',
    searchUrlTemplate: 'https://search.scielo.org/?q={query}&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1',
    highlightedJournals: [
      'Revista Brasileira de Ciência do Solo (RBCS)',
      'Pesquisa Agropecuária Brasileira (PAB)',
      'Bragantia (Instituto Agronômico de Campinas - IAC)',
      'Ciência Rural (UFSM)',
      'Revista Ceres (UFV)',
    ],
    features: ['Filtro por periódico Qualis', 'Download direto em PDF', 'Métricas de citação e DOI'],
  },
  {
    id: 'embrapa_alice',
    name: 'Embrapa - Repositório Alice',
    shortName: 'Embrapa Alice',
    organization: 'Empresa Brasileira de Pesquisa Agropecuária (MAPA)',
    description: 'Acesso Livre à Informação Científica da Embrapa: reúne artigos científicos publicados pelos pesquisadores da Embrapa em periódicos indexados nacionais e internacionais.',
    focusArea: 'Pesquisa agropecuária tropical, milho, soja, solos, bioinsumos e pastagens',
    badge: 'Referência Oficial Brasil',
    badgeColor: '#1B5E20',
    baseUrl: 'https://www.alice.cnptia.embrapa.br',
    searchUrlTemplate: 'https://www.alice.cnptia.embrapa.br/alice/handle/doc/1/discover?query={query}',
    highlightedJournals: [
      'Embrapa Milho e Sorgo (Sete Lagoas - MG)',
      'Embrapa Soja (Londrina - PR)',
      'Embrapa Solos (Rio de Janeiro - RJ)',
      'Embrapa Agrobiologia (Seropédica - RJ)',
      'Embrapa Meio Ambiente (Jaguariúna - SP)',
    ],
    features: ['Pesquisa 100% validada no campo brasileiro', 'Dados experimentais de longo prazo', 'Artigos de alto impacto'],
  },
  {
    id: 'embrapa_infoteca',
    name: 'Embrapa - Infoteca-e',
    shortName: 'Embrapa Infoteca-e',
    organization: 'Embrapa - Transferência de Tecnologia',
    description: 'Acervo de informações tecnológicas produzidas pela Embrapa para produtores rurais, engenheiros agrônomos, cooperativas e técnicos agrícolas.',
    focusArea: 'Recomendações técnicas de adubação, controle de pragas, cultivares e boletins de pesquisa',
    badge: 'Extensão & Recomendações',
    badgeColor: '#33691E',
    baseUrl: 'https://www.infoteca.cnptia.embrapa.br',
    searchUrlTemplate: 'https://www.infoteca.cnptia.embrapa.br/infoteca/handle/doc/1/discover?query={query}',
    highlightedJournals: [
      'Boletins de Pesquisa e Desenvolvimento (BPD)',
      'Circulares Técnicas Embrapa',
      'Comunicados Técnicos',
      'Documentos & Guias de Manejo',
    ],
    features: ['Linguagem técnica aplicável na fazenda', 'Tabelas práticas de calibração de doses', 'Acesso livre e gratuito'],
  },
  {
    id: 'scholar',
    name: 'Google Acadêmico (Google Scholar)',
    shortName: 'Google Acadêmico',
    organization: 'Google Scholar',
    description: 'Maior indexador global de literatura acadêmica, teses, dissertações, livros, sumários e artigos revisados por pares das principais editoras mundiais.',
    focusArea: 'Multidisciplinar, Agronomia Global, Fitopatologia, Biotecnologia e Economia Rural',
    badge: 'Indexador Global',
    badgeColor: '#1565C0',
    baseUrl: 'https://scholar.google.com.br',
    searchUrlTemplate: 'https://scholar.google.com.br/scholar?hl=pt-BR&as_sdt=0%2C5&q={query}',
    highlightedJournals: [
      'Field Crops Research',
      'Agronomy Journal (ASA)',
      'Soil and Tillage Research',
      'Crop Science',
      'Plant and Soil',
    ],
    features: ['Contador de citações de artigos', 'Links para versões em PDF abertas', 'Alertas de novas publicações'],
  },
  {
    id: 'capes',
    name: 'Portal de Periódicos CAPES',
    shortName: 'CAPES Periódicos',
    organization: 'Ministério da Educação (MEC)',
    description: 'Biblioteca virtual que reúne e disponibiliza o melhor da produção científica internacional e nacional para instituições de ensino e pesquisa no Brasil.',
    focusArea: 'Bases de dados referenciais (Web of Science, Scopus, CAB Direct)',
    badge: 'Acervo Federal',
    badgeColor: '#4527A0',
    baseUrl: 'https://www.periodicos.capes.gov.br',
    searchUrlTemplate: 'https://www.periodicos.capes.gov.br/?option=com_pbusca&task=buscaAvancada&termo={query}',
    highlightedJournals: [
      'CAB Abstracts (Centro de Agricultura e Biociências)',
      'Web of Science Core Collection',
      'SciFinder / Chemical Abstracts',
    ],
    features: ['Mais de 49 mil periódicos com texto completo', 'Acesso institucional Café/RNP', 'Bases com fator de impacto JCR'],
  },
  {
    id: 'bdtd',
    name: 'BDTD - Teses e Dissertações',
    shortName: 'BDTD / IBICT',
    organization: 'Instituto Brasileiro de Informação em Ciência e Tecnologia',
    description: 'Integra os sistemas de informação de teses e dissertações existentes nas universidades brasileiras (ESALQ/USP, UFV, UFLA, UNESP, UFRGS, etc.).',
    focusArea: 'Pesquisas de mestrado e doutorado em agronomia de ponta no Brasil',
    badge: 'Pós-Graduação',
    badgeColor: '#AD1457',
    baseUrl: 'https://bdtd.ibict.br',
    searchUrlTemplate: 'https://bdtd.ibict.br/vufind/Search/Results?lookfor={query}&type=AllFields',
    highlightedJournals: [
      'Teses ESALQ - Universidade de São Paulo',
      'Dissertações Universidade Federal de Viçosa (UFV)',
      'Teses Universidade Federal de Lavras (UFLA)',
    ],
    features: ['Pesquisas completas com metodologia detalhada', 'Dados experimentais brutos', 'Inovações recentes de doutorado'],
  },
  {
    id: 'youtube_agro',
    name: 'YouTube Técnico & Científico Agro',
    shortName: 'YouTube Agro',
    organization: 'Embrapa Oficial, AgroAdvance, Fundação MT, ESALQ/USP',
    description: 'Canal audiovisual de divulgação técnico-científica: palestras de pesquisadores, demonstrações de campo, webinars agronômicos e simpósios universitários.',
    focusArea: 'Palestras técnicas, aulas de fertilidade do solo, manejo de culturas e dias de campo',
    badge: 'Audiovisual & Prática',
    badgeColor: '#C62828',
    baseUrl: 'https://www.youtube.com',
    searchUrlTemplate: 'https://www.youtube.com/results?search_query={query}+agronomia+pesquisa',
    highlightedJournals: [
      'Canal Oficial da Embrapa',
      'AgroAdvance Ciência Agronômica',
      'Fundação MT Pesquisa Aplicada',
      'Canal do Adubo / Prof. Dr. Godofredo Vitti',
    ],
    features: ['Palestras completas com slides e dados experimentais', 'Visualização de raízes e perfis de solo', 'Linguagem didática e direta'],
  },
];
