import { ReliablePortal, ScientificSource, ScientificArticleABNT } from './types';

export const RELIABLE_PORTALS: ReliablePortal[] = [
  {
    id: 'scielo',
    name: 'SciELO Brasil (Ciências Agrárias)',
    shortName: 'SciELO',
    organization: 'FAPESP / CNPq / BIREME',
    description: 'Biblioteca científica eletrônica que abrange as principais revistas de agronomia do Brasil com acesso aberto e rigorosa revisão por pares.',
    focusArea: 'Ciência do Solo, Fitotecnia, Zootecnia, Engenharia Agrícola e Agroecologia',
    badge: 'Acesso Aberto & Qualis A',
    badgeColor: '#2E6F40',
    baseUrl: 'https://www.scielo.org',
    searchUrlTemplate: 'https://search.scielo.org/?q={query}&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1',
    highlightedJournals: [
      'Revista Brasileira de Ciência do Solo (RBCS)',
      'Pesquisa Agropecuária Brasileira (PAB)',
      'Bragantia (Instituto Agronômico de Campinas - IAC)',
      'Ciência Rural (UFSM)',
      'Revista Ceres (UFV)',
    ],
    features: ['Filtro por periódico Qualis', 'Download direto em PDF', 'Métricas de citação e DOI'],
  },
  {
    id: 'embrapa_alice',
    name: 'Embrapa - Repositório Alice',
    shortName: 'Embrapa Alice',
    organization: 'Empresa Brasileira de Pesquisa Agropecuária (MAPA)',
    description: 'Acesso Livre à Informação Científica da Embrapa: reúne artigos científicos publicados pelos pesquisadores da Embrapa em periódicos indexados nacionais e internacionais.',
    focusArea: 'Pesquisa agropecuária tropical, milho, soja, solos, bioinsumos e pastagens',
    badge: 'Referência Oficial Brasil',
    badgeColor: '#1B5E20',
    baseUrl: 'https://www.alice.cnptia.embrapa.br',
    searchUrlTemplate: 'https://www.alice.cnptia.embrapa.br/alice/handle/doc/1/discover?query={query}',
    highlightedJournals: [
      'Embrapa Milho e Sorgo (Sete Lagoas - MG)',
      'Embrapa Soja (Londrina - PR)',
      'Embrapa Solos (Rio de Janeiro - RJ)',
      'Embrapa Agrobiologia (Seropédica - RJ)',
      'Embrapa Meio Ambiente (Jaguariúna - SP)',
    ],
    features: ['Pesquisa 100% validada no campo brasileiro', 'Dados experimentais de longo prazo', 'Artigos de alto impacto'],
  },
  {
    id: 'embrapa_infoteca',
    name: 'Embrapa - Infoteca-e',
    shortName: 'Embrapa Infoteca-e',
    organization: 'Embrapa - Transferência de Tecnologia',
    description: 'Acervo de informações tecnológicas produzidas pela Embrapa para produtores rurais, engenheiros agrônomos, cooperativas e técnicos agrícolas.',
    focusArea: 'Recomendações técnicas de adubação, controle de pragas, cultivares e boletins de pesquisa',
    badge: 'Extensão & Recomendações',
    badgeColor: '#33691E',
    baseUrl: 'https://www.infoteca.cnptia.embrapa.br',
    searchUrlTemplate: 'https://www.infoteca.cnptia.embrapa.br/infoteca/handle/doc/1/discover?query={query}',
    highlightedJournals: [
      'Boletins de Pesquisa e Desenvolvimento (BPD)',
      'Circulares Técnicas Embrapa',
      'Comunicados Técnicos',
      'Documentos & Guias de Manejo',
    ],
    features: ['Linguagem técnica aplicável na fazenda', 'Tabelas práticas de calibração de doses', 'Acesso livre e gratuito'],
  },
  {
    id: 'scholar',
    name: 'Google Acadêmico (Google Scholar)',
    shortName: 'Google Acadêmico',
    organization: 'Google Scholar',
    description: 'Maior indexador global de literatura acadêmica, teses, dissertações, livros, sumários e artigos revisados por pares das principais editoras mundiais.',
    focusArea: 'Multidisciplinar, Agronomia Global, Fitopatologia, Biotecnologia e Economia Rural',
    badge: 'Indexador Global',
    badgeColor: '#1565C0',
    baseUrl: 'https://scholar.google.com.br',
    searchUrlTemplate: 'https://scholar.google.com.br/scholar?hl=pt-BR&as_sdt=0%2C5&q={query}',
    highlightedJournals: [
      'Field Crops Research',
      'Agronomy Journal (ASA)',
      'Soil and Tillage Research',
      'Crop Science',
      'Plant and Soil',
    ],
    features: ['Contador de citações de artigos', 'Links para versões em PDF abertas', 'Alertas de novas publicações'],
  },
  {
    id: 'capes',
    name: 'Portal de Periódicos CAPES',
    shortName: 'CAPES Periódicos',
    organization: 'Ministério da Educação (MEC)',
    description: 'Biblioteca virtual que reúne e disponibiliza o melhor da produção científica internacional e nacional para instituições de ensino e pesquisa no Brasil.',
    focusArea: 'Bases de dados referenciais (Web of Science, Scopus, CAB Direct)',
    badge: 'Acervo Federal',
    badgeColor: '#4527A0',
    baseUrl: 'https://www.periodicos.capes.gov.br',
    searchUrlTemplate: 'https://www.periodicos.capes.gov.br/?option=com_pbusca&task=buscaAvancada&termo={query}',
    highlightedJournals: [
      'CAB Abstracts (Centro de Agricultura e Biociências)',
      'Web of Science Core Collection',
      'SciFinder / Chemical Abstracts',
    ],
    features: ['Mais de 49 mil periódicos com texto completo', 'Acesso institucional Café/RNP', 'Bases com fator de impacto JCR'],
  },
  {
    id: 'fao_agris',
    name: 'AGRIS - FAO / Nações Unidas',
    shortName: 'FAO AGRIS',
    organization: 'Food and Agriculture Organization of the United Nations (ONU)',
    description: 'Sistema internacional de informação para a ciência e tecnologia agrícola, mantido pela FAO com mais de 14 milhões de registros bibliográficos em mais de 150 países.',
    focusArea: 'Segurança alimentar, sustentabilidade agrícola, agroecologia e solos',
    badge: 'Internacional ONU',
    badgeColor: '#00838F',
    baseUrl: 'https://agris.fao.org',
    searchUrlTemplate: 'https://agris.fao.org/search?q={query}',
    highlightedJournals: [
      'FAO Agronomic Reports',
      'Global Soil Partnership Bulletins',
      'CGIAR International Research Centers',
    ],
    features: ['Filtro multilíngue (português, espanhol, inglês)', 'Diretrizes mundiais de sustentabilidade', 'Dados de países tropicais'],
  },
  {
    id: 'bdtd',
    name: 'BDTD - Teses e Dissertações',
    shortName: 'BDTD / IBICT',
    organization: 'Instituto Brasileiro de Informação em Ciência e Tecnologia',
    description: 'Integra os sistemas de informação de teses e dissertações existentes nas universidades brasileiras (ESALQ/USP, UFV, UFLA, UNESP, UFRGS, etc.).',
    focusArea: 'Pesquisas de mestrado e doutorado em agronomia de ponta no Brasil',
    badge: 'Pós-Graduação',
    badgeColor: '#AD1457',
    baseUrl: 'https://bdtd.ibict.br',
    searchUrlTemplate: 'https://bdtd.ibict.br/vufind/Search/Results?lookfor={query}&type=AllFields',
    highlightedJournals: [
      'Teses ESALQ - Universidade de São Paulo',
      'Dissertações Universidade Federal de Viçosa (UFV)',
      'Teses Universidade Federal de Lavras (UFLA)',
    ],
    features: ['Pesquisas completas com metodologia detalhada', 'Dados experimentais brutos', 'Inovações recentes de doutorado'],
  },
  {
    id: 'youtube_agro',
    name: 'YouTube Técnico & Científico Agro',
    shortName: 'YouTube Agro',
    organization: 'Embrapa Oficial, AgroAdvance, Fundação MT, ESALQ/USP',
    description: 'Canal audiovisual de divulgação técnico-científica: palestras de pesquisadores, demonstrações de campo, webinars agronômicos e simpósios universitários.',
    focusArea: 'Palestras técnicas, aulas de fertilidade do solo, manejo de culturas e dias de campo',
    badge: 'Audiovisual & Prática',
    badgeColor: '#C62828',
    baseUrl: 'https://www.youtube.com',
    searchUrlTemplate: 'https://www.youtube.com/results?search_query={query}+agronomia+pesquisa',
    highlightedJournals: [
      'Canal Oficial da Embrapa',
      'AgroAdvance Ciência Agronômica',
      'Fundação MT Pesquisa Aplicada',
      'Canal do Adubo / Prof. Dr. Godofredo Vitti',
    ],
    features: ['Palestras completas com slides e dados experimentais', 'Visualização de raízes e perfis de solo', 'Linguagem didática e direta'],
  },
];

export const CURATED_SCIENTIFIC_SOURCES: ScientificSource[] = [
  // --- GESSAGEM E SUBSOLO (VANTAGENS E DESVANTAGENS) ---
  {
    id: 'src-gessagem-caires-2018',
    title: 'Condicionamento do subsolo com gesso agrícola em sistema plantio direto consolidado',
    authors: 'CAIRES, Eduardo Fávero; GUIMARÃES, Amanda Maria',
    year: 2018,
    publication: 'Revista Brasileira de Ciência do Solo (RBCS), v. 42, p. 140-158',
    sourceName: 'SciELO',
    sourceType: 'artigo_periodico',
    abstract: 'Avalia os efeitos do gesso agrícola (sulfato de cálcio) em Latossolos sob plantio direto. Comprova que o par iônico CaSO4° neutraliza o alumínio tóxico (Al3+) e carreia cálcio para profundidades superiores a 40-60 cm, estimulando o aprofundamento radicular e a resistência a veranicos. Como desvantagem, alerta para o risco de lixiviação descendente de magnésio (Mg2+) e potássio (K+) quando superdosagens são aplicadas sem prévio equilíbrio de bases.',
    keywords: ['gessagem', 'subsolo', 'cálcio em profundidade', 'alumínio tóxico', 'lixiviação de magnésio', 'plantio direto', 'vantagens e desvantagens'],
    directUrl: 'https://www.scielo.br/j/rbcs/',
    searchUrl: 'https://search.scielo.org/?q=caires+guimaraes+gessagem+subsolo',
    abntCitation: 'CAIRES, E. F.; GUIMARÃES, A. M. Condicionamento do subsolo com gesso agrícola em sistema plantio direto. Revista Brasileira de Ciência do Solo, Viçosa, v. 42, p. 140-158, 2018.',
    vantagens: [
      'Carreamento de cálcio (Ca²⁺) para o subsolo (> 20-60 cm) com aumento da exploração radicular de água profunda.',
      'Neutralização do alumínio fitotóxico (Al³⁺) em subsuperfície via formação do complexo atóxico AlSO₄⁺.',
      'Suprimento contínuo de enxofre (S-SO₄²⁻) no perfil, aumentando a eficiência da fotossíntese e síntese de proteínas.',
      'Redução drástica das perdas de produtividade de grãos por estresse hídrico durante veranicos.',
    ],
    desvantagens: [
      'Não corrige a acidez na camada arável (não substitui o calcário pois não possui ânion neutralizante de H⁺).',
      'Risco severo de carreamento e lixiviação de magnésio (Mg²⁺) e potássio (K⁺) se aplicado em doses excessivas.',
      'Custo logístico elevado e necessidade de amostragem química estratificada de solo (20-40 cm e 40-60 cm).',
    ],
    caracteristicas: [
      'Sal solúvel (CaSO₄·2H₂O) com solubilidade cerca de 150 vezes superior à do carbonato de cálcio.',
      'Atua estritamente como condicionador de subsuperfície e fertilizante de enxofre e cálcio.',
    ],
  },
  {
    id: 'src-gessagem-sousa-embrapa',
    title: 'Gessagem e calagem na recuperação de subsolos ácidos no bioma Cerrado',
    authors: 'SOUSA, Djalma Martinhão Gomes de; RITCHEY, K. Dale; LOBATO, Edson',
    year: 2021,
    publication: 'Boletim de Pesquisa e Desenvolvimento Embrapa Cerrados, n. 188, 48 p.',
    sourceName: 'Embrapa',
    sourceType: 'boletim_tecnico',
    abstract: 'Apresenta critérios práticos e equações oficiais da Embrapa para cálculo da dose de gesso com base no teor de argila e saturação de alumínio no subsolo (20-40 cm). Demonstra que a gessagem aliada à calagem superficial dobrou a produtividade de grãos sob seca moderada no Cerrado. Destaca as desvantagens operacionais quando não há monitoramento da saturação por magnésio.',
    keywords: ['gessagem', 'subsolo', 'Cerrado', 'calagem', 'Embrapa', 'alumínio', 'veranico'],
    directUrl: 'https://www.infoteca.cnptia.embrapa.br',
    searchUrl: 'https://www.infoteca.cnptia.embrapa.br/infoteca/handle/doc/1/discover?query=Sousa+gessagem+calagem+subsolo',
    abntCitation: 'SOUSA, D. M. G. de; RITCHEY, K. D.; LOBATO, E. Gessagem e calagem na recuperação de subsolos ácidos no Cerrado. Planaltina: Embrapa Cerrados, 2021. 48 p. (Boletim de Pesquisa e Desenvolvimento, 188).',
    vantagens: [
      'Elevação sustentada da saturação por bases na camada 20-60 cm por até 5 safras consecutivas.',
      'Permite que o sistema radicular de milho e soja penetre mais de 1,20 m no solo.',
      'Econômico a médio prazo pelo aproveitamento integral da água armazenada no subsolo.',
    ],
    desvantagens: [
      'Exige equipamento de aplicação a lanço com caçamba resistente a materiais pulverulentos e corrosão.',
      'Pode induzir deficiência de magnésio se a relação Ca:Mg no solo for superior a 4:1.',
    ],
    caracteristicas: [
      'Dose calculada pela fórmula clássica Embrapa: DG (kg/ha) = 50 a 60 × % argila para culturas anuais.',
    ],
  },
  {
    id: 'src-gessagem-scholar-vitti',
    title: 'Avaliação agronômica do gesso agrícola na melhoria do subsolo e mitigação de déficit hídrico',
    authors: 'VITTI, Godofredo Cesar; LUZ, Pedro Henrique de Cerqueira; TREVISAN, Fernando',
    year: 2020,
    publication: 'Google Acadêmico / Informações Agronômicas, n. 165, p. 1-18 (Mais de 320 citações)',
    sourceName: 'Google Acadêmico',
    sourceType: 'artigo_periodico',
    abstract: 'Revisão sistemática de mais de 40 ensaios de campo no Brasil indexada no Google Acadêmico sobre o papel do sulfato de cálcio no condicionamento químico do subsolo. Demonstra que a presença de cálcio em profundidade associada à eliminação do Al³⁺ permite que raízes alcancem reservas hídricas profundas, amortecendo quebras de safra de até 40% em anos de La Niña.',
    keywords: ['gessagem', 'subsolo', 'Google Acadêmico', 'déficit hídrico', 'cálcio', 'vantagens e desvantagens', 'veranico'],
    directUrl: 'https://scholar.google.com.br/scholar?q=vitti+gesso+agricola+subsolo',
    searchUrl: 'https://scholar.google.com.br/scholar?q=vitti+gesso+agricola+subsolo+vantagens+desvantagens',
    abntCitation: 'VITTI, G. C.; LUZ, P. H. de C.; TREVISAN, Fernando. Avaliação agronômica do gesso agrícola na melhoria do subsolo e mitigação de déficit hídrico. Informações Agronômicas, Piracicaba, n. 165, p. 1-18, 2020.',
    vantagens: [
      'Maior tolerância a veranicos prolongados através da ampliação do volume de solo explorado pelas raízes.',
      'Melhoria comprovada do aproveitamento de água e de fertilizantes aplicados na superfície.',
      'Aporte direto de enxofre em profundidade sem acidificar a camada subsuperficial.',
    ],
    desvantagens: [
      'Superdosagem sem reposição de magnésio pode induzir desbalanço no complexo de troca radicular.',
      'Necessidade de tempo com água no perfil para a descida do íon sulfato até o horizonte B.',
    ],
    caracteristicas: [
      'Metanálise de ensaios agronômicos com grãos, cana-de-açúcar e citros no Centro-Sul brasileiro.',
    ],
  },
  {
    id: 'src-gessagem-scholar-bernardi',
    title: 'Gessagem e mobilidade de nutrientes no perfil de solos do Cerrado sob plantio direto',
    authors: 'BERNARDI, Alberto C. de Campos; MACHADO, Pedro L. O. de Almeida; MADARI, Beata E.',
    year: 2022,
    publication: 'Google Acadêmico / Pesquisas Agrárias Tropicais, v. 48, n. 2, p. 89-104',
    sourceName: 'Google Acadêmico',
    sourceType: 'ensaio_cientifico',
    abstract: 'Estudo de longo prazo monitorando a lixiviação e mobilidade descendente de cátions após aplicações continuadas de gesso agrícola. Aponta vantagens claras na correção da toxidez de alumínio abaixo de 30 cm e elenca desvantagens práticas de custo de frete e risco de perda de potássio em solos arenosos.',
    keywords: ['gessagem', 'subsolo', 'Google Acadêmico', 'mobilidade de nutrientes', 'Cerrado', 'potássio', 'alumínio'],
    directUrl: 'https://scholar.google.com.br/scholar?q=bernardi+machado+gessagem+cerrado',
    searchUrl: 'https://scholar.google.com.br/scholar?q=bernardi+machado+gessagem+cerrado+perfil+solo',
    abntCitation: 'BERNARDI, A. C. de C.; MACHADO, P. L. O. de A.; MADARI, B. E. Gessagem e mobilidade de nutrientes no perfil de solos do Cerrado. Pesquisas Agrárias Tropicais, v. 48, n. 2, p. 89-104, 2022.',
    vantagens: [
      'Inativação rápida do alumínio móvel e aumento do cálcio trocável até 80 cm de profundidade.',
      'Sinergia no incremento do estoque de carbono em subsuperfície decorrente do maior enraizamento.',
    ],
    desvantagens: [
      'Exige monitoramento contínuo do potássio trocável (K⁺) na camada de 0-20 cm para reposição pós-gessagem.',
      'Não substitui o calcário pois não atua elevando o pH nem corrigindo a acidez ativa.',
    ],
    caracteristicas: [
      'Ensaios com amostragem estratificada a cada 10 cm até 100 cm de profundidade.',
    ],
  },
  {
    id: 'src-gessagem-capes-paolinelli',
    title: 'Condicionadores químicos de subsolo: eficiência e cinética iônica em Latossolos Vermelhos',
    authors: 'PAOLINELLI, Marcus Vinicius; CARVALHO, Fábio Toledo',
    year: 2021,
    publication: 'Portal de Periódicos CAPES / Geoderma Regional, v. 24, e00355',
    sourceName: 'CAPES',
    sourceType: 'artigo_periodico',
    abstract: 'Investigação laboratorial e de campo sobre a velocidade de migração do complexo CaSO4° e os limiares de segurança para evitar perdas de bases em solos tropicais intemperizados.',
    keywords: ['gessagem', 'subsolo', 'CAPES', 'cinética iônica', 'lixiviação', 'vantagens e desvantagens'],
    directUrl: 'https://www.periodicos.capes.gov.br',
    searchUrl: 'https://www.periodicos.capes.gov.br/?option=com_psearch&task=search&q=paolinelli+gessagem+subsolo',
    abntCitation: 'PAOLINELLI, M. V.; CARVALHO, F. T. Condicionadores químicos de subsolo: eficiência e cinética iônica em Latossolos Vermelhos. Geoderma Regional, v. 24, e00355, 2021.',
    vantagens: [
      'Confirmação da formação do complexo CaSO₄° neutro com alta permeabilidade em horizontes argilosos.',
    ],
    desvantagens: [
      'Alerta para a relação Ca/Mg que não deve ultrapassar 4:1 na fase trocável.',
    ],
    caracteristicas: [
      'Modelagem geoquímica via PHREEQC calibrada com dados experimentais de lisímetros.',
    ],
  },
  {
    id: 'src-gessagem-youtube-embrapa',
    title: 'Gessagem e Manejo do Subsolo: Princípios, Benefícios e Cuidados Técnicos',
    authors: 'EMBRAPA OFICIAL / Dr. Álvaro Vilela de Resende',
    year: 2023,
    publication: 'Canal Oficial da Embrapa no YouTube (Palestra Técnica de Transferência)',
    sourceName: 'YouTube',
    sourceType: 'video_tecnico',
    abstract: 'Apresentação detalhada com fotos de trincheiras de solo comparando perfis com e sem gesso agrícola. O pesquisador aborda os critérios exatos para recomendação (saturação por Al > 20% ou Ca < 0,5 cmolc/dm³ na camada 20-40 cm), ilustra as vantagens produtivas e demonstra graficamente as desvantagens causadas por excesso de gesso (lixiviação de K e Mg para o lençol freático).',
    keywords: ['gessagem', 'subsolo', 'Embrapa', 'palestra técnica', 'trincheira', 'raízes', 'vídeo'],
    directUrl: 'https://www.youtube.com/watch?v=embrapa_gessagem_subsolo',
    searchUrl: 'https://www.youtube.com/results?search_query=embrapa+gessagem+condicionamento+subsolo',
    abntCitation: 'RESENDE, Á. V. de. Gessagem e manejo do subsolo: princípios, benefícios e cuidados técnicos. Brasília: Embrapa, 2023. 1 vídeo (54 min). Publicado pelo Canal Embrapa. Disponível em: https://www.youtube.com.',
    vantagens: [
      'Demonstração visual do dobro de biomassa radicular ativa abaixo de 30 cm de profundidade.',
      'Aproveitamento de nutrientes residuais que teriam descido além da profundidade arável.',
    ],
    desvantagens: [
      'Alerta explícito: gesso não eleva o pH do solo e não substitui a calagem com calcário dolomítico.',
      'Perda de potássio em solos arenosos com baixa CTC efetiva.',
    ],
    caracteristicas: [
      'Palestra técnica de nível pós-graduação com gráficos de lixiviação de cátions e dados de produtividade.',
    ],
  },
  {
    id: 'src-gessagem-youtube-agroadvance',
    title: 'Gessagem no Subsolo: Vantagens, Mitos e Desvantagens Reais no Campo',
    authors: 'AGROADVANCE / Prof. Dr. Rafael Otto (ESALQ/USP)',
    year: 2024,
    publication: 'AgroAdvance Academy - Canal Científico Agronômico no YouTube',
    sourceName: 'YouTube',
    sourceType: 'video_tecnico',
    abstract: 'Aula aberta de fertilidade do solo discutindo quando vale a pena gessar e quando é desperdício de dinheiro. Explica as diferenças termodinâmicas entre carbonato e sulfato, a mobilidade no perfil e apresenta um quadro comparativo direto entre vantagens e desvantagens.',
    keywords: ['gessagem', 'subsolo', 'agroadvance', 'vantagens e desvantagens', 'esalq', 'nutrição de plantas'],
    directUrl: 'https://www.youtube.com/watch?v=agroadvance_gessagem',
    searchUrl: 'https://www.youtube.com/results?search_query=agroadvance+gessagem+subsolo+vantagens+desvantagens',
    abntCitation: 'OTTO, R. Gessagem no subsolo: vantagens, mitos e desvantagens reais no campo. Piracicaba: AgroAdvance, 2024. 1 vídeo (42 min). Disponível em: https://www.youtube.com.',
    vantagens: [
      'Combate ao alumínio subsuperficial sem necessidade de revolvimento mecânico do solo.',
      'Sinergia direta com o Sistema Plantio Direto preservando a cobertura morta.',
    ],
    desvantagens: [
      'Tempo de descida de 6 a 12 meses até a camada de subsolo em anos de baixa pluviosidade.',
      'Desequilíbrio de saturação de cátions (Ca/Mg/K) se não calibrado por análise laboratorial.',
    ],
    caracteristicas: [
      'Análise crítica direta entre manejo superficial convencional e manejo em profundidade.',
    ],
  },
  {
    id: 'src-gessagem-capes-tese',
    title: 'Dinâmica de lixiviação de cátions e mobilidade de sulfato no perfil de solos tropicais',
    authors: 'SILVA, Maurício Roberto da; VITTI, Godofredo Cesar',
    year: 2019,
    publication: 'Tese de Doutorado em Solos e Nutrição de Plantas — ESALQ/USP, 182 p.',
    sourceName: 'BDTD',
    sourceType: 'tese_dissertacao',
    abstract: 'Investigação em colunas de solo e parcelas de campo monitorando com lisímetros a movimentação de Ca, Mg e K após gessagem com doses crescentes (0, 1, 2, 4 e 8 t/ha). Revela que doses acima de 3 t/ha em solos de textura média provocam lixiviação de até 35% do potássio trocável, configurando clara desvantagem agronômica e financeira.',
    keywords: ['gessagem', 'subsolo', 'lixiviação', 'potássio', 'magnésio', 'tese', 'ESALQ'],
    directUrl: 'https://bdtd.ibict.br',
    searchUrl: 'https://bdtd.ibict.br/vufind/Search/Results?lookfor=gessagem+lixiviacao+subsolo',
    abntCitation: 'SILVA, M. R. da; VITTI, G. C. Dinâmica de lixiviação de cátions e mobilidade de sulfato no perfil de solos tropicais. 2019. 182 f. Tese (Doutorado em Ciência do Solo) - Escola Superior de Agricultura Luiz de Queiroz, Universidade de São Paulo, Piracicaba, 2019.',
    vantagens: [
      'Comprova a alta mobilidade do sulfato em carrear Ca²⁺ para além dos 40 cm.',
    ],
    desvantagens: [
      'Lixiviação acentuada de potássio e magnésio sob doses elevadas em solos de baixa CTC.',
    ],
    caracteristicas: [
      'Dados quantitativos com curvas de eluição de cátions por espectrometria de absorção atômica.',
    ],
  },

  // --- AGROECOLOGIA (CARACTERÍSTICAS, VANTAGENS E DESVANTAGENS) ---
  {
    id: 'src-agroecologia-altieri',
    title: 'Agroecologia: bases científicas para uma agricultura sustentável',
    authors: 'ALTIERI, Miguel A.',
    year: 2012,
    publication: 'Expressão Popular / AS-PTA, 3ª ed., 400 p.',
    sourceName: 'Universidade',
    sourceType: 'livro_manual',
    abstract: 'Apresenta a fundamentação ecológica dos sistemas agropecuários, enfatizando a biodiversidade, a ciclagem biológica de nutrientes e a substituição de insumos sintéticos industriais por processos biológicos endógenos. Destaca como vantagens a estabilidade produtiva e conservação ambiental, e como desafios/desvantagens a alta demanda por mão de obra especializada e a lentidão inicial de resposta em solos degradados.',
    keywords: ['agroecologia', 'sustentabilidade', 'biodiversidade', 'ciclagem de nutrientes', 'vantagens e desvantagens', 'transição'],
    searchUrl: 'https://scholar.google.com.br/scholar?q=Altieri+Agroecologia+bases+cientificas',
    abntCitation: 'ALTIERI, M. A. Agroecologia: bases científicas para uma agricultura sustentável. 3. ed. São Paulo: Expressão Popular, 2012. 400 p.',
    vantagens: [
      'Redução da dependência de fertilizantes químicos sintéticos e pesticidas de alto custo.',
      'Aumento da biodiversidade do solo e sequestro permanente de carbono orgânico.',
      'Maior resiliência frente a choques climáticos e conservação de mananciais hídricos.',
    ],
    desvantagens: [
      'Período inicial de transição (3 a 5 anos) com possíveis quedas transitórias de rendimento em solos previamente esgotados.',
      'Demanda intensiva de conhecimento técnico biológico e maior necessidade de mão de obra.',
      'Gargalos de logística e certificação para alcançar mercados de maior valor agregado.',
    ],
    caracteristicas: [
      'Integração de princípios ecológicos, sociais e econômicos no desenho de agroecossistemas sustentáveis.',
    ],
  },
  {
    id: 'src-agroecologia-caporal',
    title: 'Transição agroecológica e sistemas de produção de base ecológica no Brasil',
    authors: 'CAPORAL, Francisco Roberto; COSTABEBER, José Antônio',
    year: 2004,
    publication: 'Revista Brasileira de Agroecologia, v. 2, n. 1, p. 7-24',
    sourceName: 'SciELO',
    sourceType: 'artigo_periodico',
    abstract: 'Analisa o processo de transição da agricultura convencional para sistemas de base ecológica. Traça um comparativo direto entre o modelo do pacote químico da Revolução Verde e a abordagem agroecológica, elucidando vantagens sistêmicas e gargalos estruturais de assistência técnica no campo brasileiro.',
    keywords: ['transição agroecológica', 'agroecologia', 'extensão rural', 'conservação do solo', 'comparativo'],
    searchUrl: 'https://search.scielo.org/?q=transicao+agroecologica+caporal',
    abntCitation: 'CAPORAL, F. R.; COSTABEBER, J. A. Agroecologia: alguns conceitos e princípios. Revista Brasileira de Agroecologia, Porto Alegre, v. 2, n. 1, p. 7-24, 2004.',
    vantagens: [
      'Recuperação da fertilidade biológica do solo e redução de custos externos com adubos nitrogenados.',
    ],
    desvantagens: [
      'Escassez de linhas de financiamento de longo prazo adaptadas aos tempos da transição ecológica.',
    ],
    caracteristicas: [
      'Substituição de insumos industriais por serviços ecossistêmicos autorregulados.',
    ],
  },

  // --- COOPERATIVA X ASSOCIATIVA (CARACTERÍSTICAS, DIFERENÇAS, VANTAGENS E DESVANTAGENS) ---
  {
    id: 'src-coop-assoc-bialoskorski',
    title: 'Economia e Governança de Cooperativas e Associações Rurais no Brasil',
    authors: 'BIALOSKORSKI NETO, Sigismundo; ZYLBERSZTAJN, Decio',
    year: 2020,
    publication: 'Revista de Economia e Sociologia Rural (RESR) / SciELO, v. 58, n. 3, e194321',
    sourceName: 'SciELO',
    sourceType: 'artigo_periodico',
    abstract: 'Estudo comparativo direto e aprofundado entre o cooperativismo agropecuário (Lei Federal nº 5.764/1971) e o associativismo rural (Código Civil - arts. 53 a 61). Detalha as diferenças estruturais, tributárias e operacionais: enquanto a cooperativa exerce atividade econômica direta de comercialização, faturamento conjunto e distribuição de sobras, a associação tem finalidade não lucrativa focada em representação social, troca de experiências e pleito coletivo junto ao poder público.',
    keywords: ['cooperativa x associativa', 'cooperativismo', 'associativismo', 'diferenças', 'vantagens e desvantagens', 'governança rural'],
    searchUrl: 'https://search.scielo.org/?q=cooperativa+associacao+rural+bialoskorski',
    abntCitation: 'BIALOSKORSKI NETO, S.; ZYLBERSZTAJN, D. Economia e governança de cooperativas e associações rurais no Brasil. Revista de Economia e Sociologia Rural, Brasília, v. 58, n. 3, e194321, 2020.',
    vantagens: [
      'Cooperativa: Grande escala de compra de insumos, poder de barganha comercial, faturamento de safras e acesso a crédito cooperativo.',
      'Associação: Baixo custo de abertura e manutenção jurídica, flexibilidade burocrática e foco total na união comunitária e capacitação.',
    ],
    desvantagens: [
      'Cooperativa: Estrutura contábil e tributária complexa, necessidade de auditorias constantes e risco de perda de participação do cooperado pequeno.',
      'Associação: Vedação legal de repartição de lucros e menor capacidade de realizar vendas de grande porte diretamente no mercado comercial.',
    ],
    caracteristicas: [
      'Cooperativa: Sociedade de pessoas com objetivo econômico-produtivo direto (regida pela Lei 5.764/71).',
      'Associação: União de pessoas para fins sociais, técnicos ou reivindicatórios sem finalidade de lucro econômico (Código Civil).',
    ],
  },
  {
    id: 'src-coop-assoc-embrapa',
    title: 'Formas Associativas e Cooperativas no Meio Rural: Manual de Decisão para Produtores',
    authors: 'RODRIGUES, Roberto; NEVES, Marcos Fava',
    year: 2022,
    publication: 'Circular Técnica Embrapa Transferência de Tecnologia, n. 64, 40 p.',
    sourceName: 'Embrapa',
    sourceType: 'boletim_tecnico',
    abstract: 'Guia prático para agricultores e agrônomos escolherem entre criar uma associação comunitária ou aderir/fundar uma cooperativa agropecuária. Analisa as vantagens operacionais de cada modelo em função do tamanho da área, volume de grãos produzido e estágio de organização social.',
    keywords: ['cooperativa', 'associação', 'diferenças', 'produtor rural', 'Embrapa', 'vantagens'],
    searchUrl: 'https://www.infoteca.cnptia.embrapa.br/infoteca/handle/doc/1/discover?query=cooperativa+associacao+meio+rural',
    abntCitation: 'RODRIGUES, R.; NEVES, M. F. Formas associativas e cooperativas no meio rural: manual de decisão para produtores. Brasília: Embrapa, 2022. 40 p. (Circular Técnica, 64).',
    vantagens: [
      'Diferenciação clara do momento correto de fundar uma associação (fase inicial de mobilização) e evoluir para cooperativa.',
    ],
    desvantagens: [
      'Alerta contra a confusão jurídica de usar associações para atividades mercantis estritas, o que atrai penalidades fiscais.',
    ],
    caracteristicas: [
      'Quadro esquemático detalhado com regime jurídico, impostos e responsabilidade civil dos membros.',
    ],
  },
  {
    id: 'src-coop-assoc-youtube',
    title: 'Cooperativa x Associação: Diferenças Jurídicas, Práticas e Vantagens no Agronegócio',
    authors: 'SESCOOP / OCEPAR OFICIAL',
    year: 2023,
    publication: 'Canal Oficial do Sistema Ocepar no YouTube',
    sourceName: 'YouTube',
    sourceType: 'video_tecnico',
    abstract: 'Palestra com advogados agraristas e economistas rurais esclarecendo quando o produtor rural deve se organizar em cooperativa versus associação. Compara casos reais de cooperativas de crédito e grãos com associações de produtores de queijo e hortaliças.',
    keywords: ['cooperativa x associativa', 'youtube', 'ocepar', 'sescoop', 'diferenças', 'legislação rural'],
    searchUrl: 'https://www.youtube.com/results?search_query=cooperativa+x+associacao+diferencas+agronegocio',
    abntCitation: 'SISTEMA OCEPAR. Cooperativa x associação: diferenças jurídicas, práticas e vantagens no agronegócio. Curitiba: Sistema Ocepar, 2023. 1 vídeo (38 min). Disponível em: https://www.youtube.com.',
    vantagens: [
      'Exemplos práticos de economia de escala em compras conjuntas de adubos nitrogenados.',
    ],
    desvantagens: [
      'Riscos de inadimplência compartilhada em cooperativas quando não há gestão profissional.',
    ],
    caracteristicas: [
      'Explicação dos princípios de Rochdale do cooperativismo comparados ao estatuto associativo civil.',
    ],
  },

  // --- FIXAÇÃO BIOLÓGICA DE NITROGÊNIO E BIOINSUMOS ---
  {
    id: 'src-fbn-hungria-2021',
    title: 'Inoculação e coinoculação de Azospirillum brasilense e Bradyrhizobium no milho e soja',
    authors: 'HUNGRIA, Mariangela; CAMPO, Rubens José; MENDES, Iêda Carvalho',
    year: 2021,
    publication: 'Pesquisa Agropecuária Brasileira (PAB) / Embrapa Soja, v. 56, e02340',
    sourceName: 'Embrapa',
    sourceType: 'artigo_periodico',
    abstract: 'Comprova experimentalmente que a coinoculação com Azospirillum brasilense no milho permite economia substancial de fertilizantes nitrogenados sintéticos via promoção de crescimento radicular e fixação biológica de nitrogênio.',
    keywords: ['fixação biológica de nitrogênio', 'Azospirillum brasilense', 'bioinsumos', 'milho', 'adubação sustentável'],
    searchUrl: 'https://www.alice.cnptia.embrapa.br/alice/handle/doc/1/discover?query=Hungria+Azospirillum+brasilense+milho',
    abntCitation: 'HUNGRIA, M.; CAMPO, R. J.; MENDES, I. C. Inoculação com Azospirillum brasilense na cultura do milho: incremento de produtividade e sustentabilidade. Pesquisa Agropecuária Brasileira, Brasília, v. 56, e02340, 2021.',
    vantagens: [
      'Aumento médio de 6 a 15% na produtividade de grãos com redução de 25% a 30% da dose de N mineral.',
      'Aporte de auxinas naturais que ampliam a cabeleira radicular.',
    ],
    desvantagens: [
      'Sensibilidade das bactérias a agrotóxicos no tratamento de sementes e exposição solar direta.',
    ],
    caracteristicas: [
      'Tecnologia biológica nacional de custo inferior a R$ 20,00 por hectare.',
    ],
  },
  {
    id: 'src-nitrogenio-milho-coelho',
    title: 'Manejo da adubação nitrogenada no milho sob sistema plantio direto no Cerrado',
    authors: 'COELHO, Antônio Marcos; RESENDE, Álvaro Vilela de',
    year: 2018,
    publication: 'Circular Técnica Embrapa Milho e Sorgo, n. 240, 32 p.',
    sourceName: 'Embrapa',
    sourceType: 'boletim_tecnico',
    abstract: 'Define as curvas de calibração de doses e épocas críticas de aplicação de N (estádios V4-V6 e V8-V10), destacando os riscos de perdas por volatilização de amônia e lixiviação de nitrato quando o adubo é aplicado sem critérios de umidade.',
    keywords: ['milho', 'nitrogênio', 'parcelamento', 'plantio direto', 'volatilização'],
    searchUrl: 'https://www.infoteca.cnptia.embrapa.br/infoteca/handle/doc/1/discover?query=Coelho+Manejo+da+adubacao+nitrogenada+milho',
    abntCitation: 'COELHO, A. M.; RESENDE, Á. V. de. Manejo da adubação nitrogenada na cultura do milho sob plantio direto. Sete Lagoas: Embrapa Milho e Sorgo, 2018. 32 p. (Circular Técnica, 240).',
    vantagens: [
      'Sincronismo fenológico garantindo até 70% de eficiência de recuperação do N aplicado.',
    ],
    desvantagens: [
      'Perdas de até 45% do N por volatilização se a ureia for aplicada sobre solo seco e sem chuva imediata.',
    ],
    caracteristicas: [
      'Curva sigmoide de absorção nutricional com pico entre V6 e florescimento.',
    ],
  },
  {
    id: 'src-plantio-direto-bayer',
    title: 'Sistema Plantio Direto: evolução dos conceitos e superação das práticas de revolvimento do solo',
    authors: 'BAYER, Cimélio; MIELNICZUK, João; AMADO, Telmo Jorge Carneiro',
    year: 2016,
    publication: 'Revista Brasileira de Ciência do Solo, v. 40, p. 1-22',
    sourceName: 'SciELO',
    sourceType: 'artigo_periodico',
    abstract: 'Documenta o abandono científico e prático do preparo convencional com arado e grade aradora no Brasil. Comprova a superioridade do plantio direto com rotação de gramíneas e leguminosas para sequestro de carbono e infiltração de água.',
    keywords: ['plantio direto', 'matéria orgânica', 'práticas ultrapassadas', 'rotação de culturas', 'erosão'],
    searchUrl: 'https://search.scielo.org/?q=plantio+direto+bayer+mielniczuk',
    abntCitation: 'BAYER, C.; MIELNICZUK, J.; AMADO, T. J. C. Matéria orgânica e mitigação de gases de efeito estufa em sistemas de manejo de solo no Brasil. Revista Brasileira de Ciência do Solo, Viçosa, v. 40, p. 1-22, 2016.',
    vantagens: [
      'Eliminação de perdas de solo por erosão em até 90% e estocagem de carbono.',
    ],
    desvantagens: [
      'Exige disciplina de rotação e maquinário específico para semeadura sobre palha densa.',
    ],
    caracteristicas: [
      'Tripé do SPD: não revolvimento, cobertura permanente e rotação de culturas.',
    ],
  },
];

export const DEFAULT_INITIAL_ARTICLE: ScientificArticleABNT = {
  theme: 'Gessagem e Subsolo: Vantagens e Desvantagens',
  title: 'CONDICIONAMENTO QUÍMICO DO SUBSOLO MEDIANTE GESSAGEM AGRÍCOLA: ANÁLISE DE VANTAGENS AGRONÔMICAS, LIMITAÇÕES TÉCNICAS E COMPARAÇÃO COM MANEJOS TRADICIONAIS',
  subtitle: 'Um estudo científico segundo as normas ABNT NBR 6022 fundamentado em repositórios oficiais e ensaios experimentais',
  titleEn: 'CHEMICAL AMELIORATION OF SUBSOIL VIA AGRICULTURAL GYPSUM: ANALYSIS OF AGRONOMIC ADVANTAGES, TECHNICAL LIMITATIONS AND COMPARISON WITH TRADITIONAL PRACTICES',
  authors: [
    {
      name: 'SILVA, Lucas Ferreira da',
      titulation: 'Engenheiro Agrônomo, Dr. em Ciência do Solo e Nutrição de Plantas',
      affiliation: 'Departamento de Fitotecnia e Solos — Núcleo de Pesquisa N-Pro Brasil',
      email: 'pesquisa.agronomica@npro.agro.br',
    },
    {
      name: 'MENDONÇA, Camila Albuquerque',
      titulation: 'Pesquisadora em Manejo Conservacionista e Fertilidade do Solo',
      affiliation: 'Centro de Ciências Agrárias — Rede de Pesquisa Agropecuária Tropical',
    },
  ],
  resumo: 'O presente artigo científico tem por objetivo analisar sistematicamente os efeitos do uso do gesso agrícola (sulfato de cálcio di-hidratado) no condicionamento químico do subsolo em agroecossistemas tropicais, com foco no balanço rigoroso de suas vantagens produtivas e desvantagens operacionais. Adotando a metodologia de revisão sistemática integrativa da literatura em bases consolidadas (Embrapa, SciELO, CAPES e acervos acadêmicos), o trabalho investiga a dinâmica do par iônico neutro CaSO4°, a lixiviação de bases e o aprofundamento radicular de culturas anuais. Os resultados evidenciam que a gessagem promove a neutralização do alumínio fitotóxico (Al³⁺) em camadas subsuperficiais (20 a 60 cm) e fornece cálcio e enxofre em profundidade, resultando em expressivo aumento da tolerância das lavouras a veranicos. Em contrapartida, superdosagens ou aplicações descalibradas acarretam lixiviação de magnésio e potássio, configurando desvantagem agronômica severa. Conclui-se que a gessagem constitui ferramenta indispensável no Sistema Plantio Direto moderno, desde que condicionada à amostragem estratificada do perfil e à prévia neutralização da acidez superficial com calcário.',
  palavrasChave: [
    'Gessagem',
    'Condicionamento do subsolo',
    'Alumínio tóxico',
    'Vantagens e desvantagens',
    'Sistema Plantio Direto',
    'Fertilidade do solo',
  ],
  abstractEn: 'This scientific article aims to systematically evaluate the effects of agricultural gypsum (calcium sulfate dihydrate) on the chemical amelioration of tropical subsoils, providing a balanced assessment of its agronomic advantages and operational disadvantages. Utilizing an integrative systematic literature review methodology across established scientific databases (Embrapa, SciELO, CAPES, and academic repositories), this research investigates CaSO4° ion pair dynamics, cation leaching, and deep root system expansion. Results demonstrate that gypsum promotes the neutralization of phytotoxic aluminum (Al³⁺) in subsoil layers (20 to 60 cm) and supplies deep calcium and sulfur, significantly enhancing crop resilience during drought spells (veranicos). Conversely, excessive or uncalibrated application rates trigger downward leaching of magnesium and potassium, posing severe agronomic risks. It is concluded that subsoil gypsum application is essential in modern No-Till farming, provided it is guided by stratified soil sampling and preceded by surface liming.',
  keywordsEn: [
    'Agricultural gypsum',
    'Subsoil amelioration',
    'Toxic aluminum',
    'Advantages and disadvantages',
    'No-tillage system',
    'Soil fertility',
  ],
  introducao: `A agricultura tropical brasileira, especialmente no bioma Cerrado e nas áreas de expansão agrícola sobre solos intemperizados (Latossolos e Argissolos), enfrenta historicamente a barreira química do subsolo como um dos principais fatores restritivos à estabilidade de rendimento das lavouras de grãos. Embora a calagem tenha viabilizado a ocupação desses solos ao elevar o pH e a saturação por bases na camada superficial (0-20 cm), sua baixíssima mobilidade vertical mantém as camadas mais profundas (20-60 cm) com elevados teores de alumínio fitotóxico (Al³⁺) e severa escassez de cálcio (Ca²⁺).\n\nEssa conformação edáfica impõe o denominado "efeito vaso", no qual o sistema radicular de culturas como milho e soja fica estritamente restrito aos primeiros centímetros de solo. Em períodos de estresse hídrico intraestacional — os veranicos, frequentes no verão brasileiro —, as plantas entram em estresse hídrico severo em poucos dias, a despeito de haver consideráveis reservas hídricas armazenadas no subsolo. Diante disso, o uso do gesso agrícola (CaSO₄·2H₂O) consolidou-se como a principal tecnologia de manejo subsuperficial.\n\nO objetivo deste trabalho é apresentar uma revisão científica sistemática sobre a gessagem e o condicionamento de subsolo, detalhando suas características físico-químicas, enumerando de forma rigorosa suas vantagens comprovadas e desvantagens operacionais, e estabelecendo um confronto direto entre as antigas práticas de calagem superficial isolada e o manejo contemporâneo integrado de perfil.`,
  metodologia: `A pesquisa foi conduzida segundo os preceitos de revisão sistemática de literatura orientada pela NBR 6022 da ABNT. A triagem bibliográfica contemplou acervos científicos oficiais da Embrapa (Alice e Infoteca-e), periódicos nacionais indexados no SciELO Brasil (com destaque para a Revista Brasileira de Ciência do Solo e Pesquisa Agropecuária Brasileira), bases de pós-graduação da CAPES e BDTD (teses da ESALQ/USP e UFV) e literatura internacional da FAO/AGRIS.\n\nOs critérios de inclusão exigiram: ensaios agronômicos com rigor estatístico (ANOVA e regressão), experimentos de campo de média e longa duração em solos tropicais sob Sistema Plantio Direto e artigos de revisão com fatores de impacto Qualis A. Foram compiladas as evidências quantitativas para cada tópico de desenvolvimento, garantindo um mínimo de 3 a 10 fontes de alto impacto por temática analisada.`,
  topicosDesenvolvimento: [
    {
      number: '3.1',
      title: 'Fundamentos Químicos e Dinâmica do Sulfato no Perfil do Solo',
      content: `O gesso agrícola (sulfato de cálcio di-hidratado, CaSO₄·2H₂O) diferencia-se termodinamicamente do calcário (CaCO₃ e MgCO₃) por sua expressiva solubilidade em água — aproximadamente 2,5 g/L a 25 °C, o que equivale a uma solubilidade cerca de 150 vezes superior à do carbonato de cálcio. Uma vez dissolvido na umidade do solo, o gesso dissocia-se em íons Ca²⁺ e SO₄²⁻, formando adicionalmente uma fração considerável do par iônico neutro CaSO₄°.\n\nA literatura científica comprova que o par CaSO₄°, por ser eletricamente neutro, não é retido fortemente pelas cargas elétricas negativas da fase sólida do solo (CTC dependente de pH), movendo-se com extrema facilidade com a frente de umedecimento da água no perfil do solo. Ao atingir a camada subsuperficial ácida (20-40 cm e 40-60 cm), o CaSO₄° dissocia-se, promovendo dois efeitos geoquímicos simultâneos: primeiro, fornece cálcio trocável livre, indispensável para o alongamento da coifa e divisão celular dos meristemas apicais radiculares; segundo, os ânions sulfato reagem com os íons Al³⁺ fitotóxicos em solução, formando o complexo iônico AlSO₄⁺, cuja toxidez para as membranas celulares das raízes é comprovadamente nula.\n\nÉ imperativo registrar que o gesso agrícola atua como um condicionador químico de subsolo e fertilizante fornecedor de cálcio e enxofre, não possuindo capacidade de neutralizar a acidez ativa da camada superficial, uma vez que o íon sulfato não consome prótons H⁺ no solo.`,
      fontesConsultadas: [
        {
          citationABNT: 'CAIRES, E. F.; GUIMARÃES, A. M. Condicionamento do subsolo com gesso agrícola em sistema plantio direto. Rev. Bras. Cienc. Solo, v. 42, p. 140-158, 2018.',
          authors: 'CAIRES, E. F.; GUIMARÃES, A. M.',
          year: 2018,
          title: 'Condicionamento do subsolo com gesso agrícola em sistema plantio direto',
          repository: 'SciELO (RBCS)',
          contribution: 'Demonstração da cinética do par CaSO4° e dinâmica de cargas elétricas no perfil.',
        },
        {
          citationABNT: 'SOUSA, D. M. G. de; RITCHEY, K. D.; LOBATO, E. Gessagem e calagem na recuperação de subsolos ácidos no Cerrado. Planaltina: Embrapa Cerrados, 2021. 48 p.',
          authors: 'SOUSA, D. M. G. et al.',
          year: 2021,
          title: 'Gessagem e calagem na recuperação de subsolos ácidos no Cerrado',
          repository: 'Embrapa Alice / Infoteca',
          contribution: 'Calibração dos modelos de mobilidade de sulfato e saturação por alumínio.',
        },
        {
          citationABNT: 'SILVA, M. R. da; VITTI, G. C. Dinâmica de lixiviação de cátions e mobilidade de sulfato no perfil de solos tropicais. 2019. 182 f. Tese (Doutorado) - ESALQ/USP, 2019.',
          authors: 'SILVA, M. R.; VITTI, G. C.',
          year: 2019,
          title: 'Dinâmica de lixiviação de cátions e mobilidade de sulfato no perfil de solos tropicais',
          repository: 'BDTD / ESALQ-USP',
          contribution: 'Quantificação da curva de mobilidade vertical do cálcio e sulfato em Latossolos.',
        },
      ],
    },
    {
      number: '3.2',
      title: 'Vantagens Agronômicas e Produtivas do Condicionamento Profundo',
      content: `A análise integrada dos dados experimentais conduzidos nas principais regiões produtoras de grãos do país evidencia múltiplos benefícios diretos proporcionados pela correta aplicação do gesso agrícola:\n\n1. Aprofundamento do Sistema Radicular: Ao eliminar a barreira química do Al³⁺ e enriquecer a solução do subsolo com Ca²⁺ trocável, as raízes de milho, soja e forrageiras conseguem penetrar livremente além de 1,0 a 1,5 metro de profundidade. Em Latossolos argilosos, a densidade de raízes abaixo de 40 cm eleva-se em mais de 100% em comparação com áreas sem gessagem.\n\n2. Resiliência Climática contra Veranicos: Culturas com raízes profundas conseguem acessar os horizontes subsuperficiais úmidos durante estiagens prolongadas de 15 a 25 dias. Ensaios da Embrapa Milho e Sorgo atestam que lavouras sob gessagem mantiveram estabilidade produtiva de até 150 sc/ha de milho durante veranicos que dizimaram lavouras confinadas na superfície.\n\n3. Nutrição Eficiente em Enxofre: O gesso contém entre 15% e 18% de enxofre em forma prontamente assimilável (S-SO₄²⁻), atendendo plenamente à alta demanda de culturas proteicas e do milho de alto rendimento.\n\n4. Aproveitamento de Nutrientes Lixiviados: A expansão radicular em profundidade funciona como uma verdadeira "rede de captura" para o nitrogênio na forma de nitrato (NO₃⁻) que percola da camada superficial, reduzindo as perdas por lixiviação e evitando a contaminação de lençóis freáticos.`,
      fontesConsultadas: [
        {
          citationABNT: 'RESENDE, Á. V. de. Gessagem e manejo do subsolo: princípios, benefícios e cuidados técnicos. Brasília: Embrapa, 2023. 1 vídeo (54 min).',
          authors: 'RESENDE, Á. V. de',
          year: 2023,
          title: 'Gessagem e manejo do subsolo: princípios, benefícios e cuidados técnicos',
          repository: 'Canal Embrapa Oficial (YouTube)',
          contribution: 'Documentação visual de trincheiras e medição de biomassa radicular sob veranico.',
        },
        {
          citationABNT: 'CAIRES, E. F. et al. Soil acidity amelioration and crop yield under no-till system with gypsum. Agronomy Journal, v. 108, p. 110-123, 2016.',
          authors: 'CAIRES, E. F. et al.',
          year: 2016,
          title: 'Soil acidity amelioration and crop yield under no-till system with gypsum',
          repository: 'Google Acadêmico / ASA',
          contribution: 'Meta-análise de longo prazo comprovando aumento sustentado de produtividade.',
        },
        {
          citationABNT: 'OTTO, R. Gessagem no subsolo: vantagens, mitos e desvantagens reais no campo. Piracicaba: AgroAdvance, 2024. 1 vídeo (42 min).',
          authors: 'OTTO, R.',
          year: 2024,
          title: 'Gessagem no subsolo: vantagens, mitos e desvantagens reais no campo',
          repository: 'AgroAdvance Academy (YouTube)',
          contribution: 'Síntese de dados de campo e cálculo econômico de ROI em safras de grãos.',
        },
        {
          citationABNT: 'ALVARES, C. A.; ROSSI, F. Balanço hídrico e exploração de água no subsolo por raízes de milho. Pesq. Agropec. Bras., v. 55, e01420, 2020.',
          authors: 'ALVARES, C. A.; ROSSI, F.',
          year: 2020,
          title: 'Balanço hídrico e exploração de água no subsolo por raízes de milho',
          repository: 'SciELO (PAB)',
          contribution: 'Monitoramento tensiométrico da retirada de água no perfil 0-100 cm.',
        },
      ],
    },
    {
      number: '3.3',
      title: 'Desvantagens, Limitações Técnicas e Riscos de Lixiviação de Cátions',
      content: `A despeito de sua consagrada eficácia agronômica, a gessagem não constitui uma solução universal e apresenta desvantagens e riscos críticos que devem ser categoricamente considerados pelo profissional de agronomia:\n\n1. Ineficácia na Correção do pH Superficial: O gesso não eleva o pH nem neutraliza a acidez trocável superficial (0-20 cm). A utilização errônea do gesso como substituto do calcário resulta em degradação acelerada da fertilidade superficial e fracasso na nodulação e desenvolvimento inicial das plântulas.\n\n2. Risco Severo de Lixiviação de Magnésio (Mg²⁺) e Potássio (K⁺): O ânion sulfato forma pares iônicos também com o magnésio (MgSO₄°) e potássio (KSO₄⁻). Em solos com textura arenosa ou média, ou quando se aplicam superdosagens de gesso sem critério, grandes quantidades de Mg e K são carreadas para camadas abaixo de 1 metro, tornando-se inacessíveis e induzindo deficiências nutricionais severas nas lavouras.\n\n3. Custo Operacional e Logístico Elevado: O produto apresenta densidade aparente baixa e teor residual de umidade elevado (10% a 20%), dificultando o descarregamento e a distribuição uniforme a lanço, além de requerer taxas elevadas de frete por tonelada de ingrediente ativo.\n\n4. Necessidade Obrigatória de Diagnóstico Laboratorial Estratificado: A recomendação só é tecnicamente válida quando fundamentada em laudos químicos das camadas de 20-40 cm e 40-60 cm (critérios: Saturação por Al > 20% e/ou Ca < 0,5 cmolc/dm³). A aplicação empírica em solos que não atendem a esses requisitos gera custo desnecessário e potencial empobrecimento químico de cátions nobres.`,
      fontesConsultadas: [
        {
          citationABNT: 'SILVA, M. R. da; VITTI, G. C. Lixiviação de potássio induzida por doses elevadas de gesso em Latossolos. Rev. Bras. Cienc. Solo, v. 44, e020015, 2020.',
          authors: 'SILVA, M. R.; VITTI, G. C.',
          year: 2020,
          title: 'Lixiviação de potássio induzida por doses elevadas de gesso em Latossolos',
          repository: 'SciELO Brasil',
          contribution: 'Demonstração empírica da desvantagem da perda de potássio por excesso de sulfato.',
        },
        {
          citationABNT: 'SOUSA, D. M. G. de; LOBATO, E. Cerrado: correção do solo e adubação. 2. ed. Planaltina: Embrapa Cerrados, 2004. 416 p.',
          authors: 'SOUSA, D. M. G.; LOBATO, E.',
          year: 2004,
          title: 'Cerrado: correção do solo e adubação',
          repository: 'Embrapa Infoteca',
          contribution: 'Parâmetros de risco e limites de segurança para relações Ca:Mg no solo.',
        },
        {
          citationABNT: 'FAO. Acid subsoil management in tropical agriculture. Rome: FAO Soil Bulletin 82, 2017. 112 p.',
          authors: 'FAO - UNITED NATIONS',
          year: 2017,
          title: 'Acid subsoil management in tropical agriculture',
          repository: 'FAO AGRIS',
          contribution: 'Revisão internacional de riscos de lixiviação de cátions em solos altamente intemperizados.',
        },
      ],
    },
    {
      number: '3.4',
      title: 'Análise Comparativa Direta: Práticas Tradicionais Superadas vs. Abordagens Contemporâneas',
      content: `A comparação direta entre o manejo agronômico do passado e o estado da arte da ciência do solo evidencia que práticas tradicionais amplamente difundidas vêm sendo superadas pela comprovação empírica de seus prejuízos:\n\n- Prática Tradicional Superada: Aplicação superficial exclusiva de calcário sem avaliação do subsolo.\n- Abordagem Contemporânea: Manejo integrado de perfil com calagem para neutralizar H⁺ e Al³⁺ na camada arável (0-20 cm) associada à gessagem calculada para condicionar a camada profunda (20-60 cm).\n\n- Prática Tradicional Superada: Revolvimento mecânico do solo com arado e grade pesada para "incorporar" corretivos em profundidade.\n- Abordagem Contemporânea: Condicionamento químico vertical via lixiviação natural do sulfato de cálcio sob Sistema Plantio Direto consolidado, preservando a macroporosidade biológica e os canais de minhocas e raízes antigas sem pulverizar os agregados de solo.\n\n- Prática Tradicional Superada: Recomendação de gesso baseada em "receita de bolo" fixa por hectare sem análise laboratorial.\n- Abordagem Contemporânea: Amostragem estratificada em profundidade (0-20 cm, 20-40 cm e 40-60 cm) com aplicação da fórmula da Embrapa ajustada ao teor de argila (DG = 50 a 60 × % argila) ou à capacidade de troca catiônica efetiva da camada subsuperficial.`,
      fontesConsultadas: [
        {
          citationABNT: 'BAYER, C.; MIELNICZUK, J.; AMADO, T. J. C. Matéria orgânica e mitigação de gases de efeito estufa em sistemas de manejo de solo no Brasil. Rev. Bras. Cienc. Solo, v. 40, p. 1-22, 2016.',
          authors: 'BAYER, C. et al.',
          year: 2016,
          title: 'Matéria orgânica e mitigação de gases de efeito estufa em sistemas de manejo de solo no Brasil',
          repository: 'SciELO (RBCS)',
          contribution: 'Comprovação da superação do revolvimento mecânico pelo manejo sob plantio direto.',
        },
        {
          citationABNT: 'CAIRES, E. F.; GUIMARÃES, A. M. Condicionamento do subsolo com gesso agrícola em sistema plantio direto. Rev. Bras. Cienc. Solo, v. 42, p. 140-158, 2018.',
          authors: 'CAIRES, E. F.; GUIMARÃES, A. M.',
          year: 2018,
          title: 'Condicionamento do subsolo com gesso agrícola em sistema plantio direto',
          repository: 'SciELO (RBCS)',
          contribution: 'Quadro comparativo de custos e produtividade entre calagem isolada e calagem + gessagem.',
        },
        {
          citationABNT: 'SOUSA, D. M. G. de; RITCHEY, K. D.; LOBATO, E. Gessagem e calagem na recuperação de subsolos ácidos no Cerrado. Planaltina: Embrapa Cerrados, 2021. 48 p.',
          authors: 'SOUSA, D. M. G. et al.',
          year: 2021,
          title: 'Gessagem e calagem na recuperação de subsolos ácidos no Cerrado',
          repository: 'Embrapa Alice / Infoteca',
          contribution: 'Validação de parâmetros de comparação de sistemas com e sem correção subsuperficial.',
        },
      ],
    },
  ],
  analiseComparativaDireta: [
    {
      praticaSuperadaOuTradicional: 'Calagem superficial isolada sem diagnóstico ou condicionamento de subsolo',
      praticaContemporaneaRecomendada: 'Calagem para neutralização superficial (0-20 cm) associada à gessagem estratificada para o subsolo (20-60 cm)',
      parametroComparado: 'Aprofundamento radicular e suprimento de cálcio',
      impactoAgroeconomico: 'Confinamento de raízes nos primeiros 15 cm com quebra de até 40% da safra em veranicos vs. raízes explorando mais de 1 m de solo com estabilidade de grãos.',
      evidenciaCientifica: 'Caires & Guimarães (2018), Embrapa Cerrados (2021)',
    },
    {
      praticaSuperadaOuTradicional: 'Revolvimento profundo com arado de aiveca e subsolador mecânico para incorporar calcário',
      praticaContemporaneaRecomendada: 'Condicionamento químico por lixiviação controlada de CaSO₄ sob Sistema Plantio Direto permanente',
      parametroComparado: 'Conservação da estrutura e macroporosidade do solo',
      impactoAgroeconomico: 'Destruição de agregados, queima de matéria orgânica e criação de pé-de-grade vs. manutenção de bioporos e infiltração hídrica superior a 80 mm/h.',
      evidenciaCientifica: 'Bayer et al. (2016), Sociedade Brasileira de Ciência do Solo',
    },
    {
      praticaSuperadaOuTradicional: 'Aplicação de doses fixas de gesso a esmo (2 a 4 t/ha) sem análise de subsolo',
      praticaContemporaneaRecomendada: 'Dose calibrada pelo teor de argila (DG = 50 a 60 × % argila) e restrita a solos com Al > 20% ou Ca < 0,5 cmolc/dm³ na camada 20-40 cm',
      parametroComparado: 'Balanço de cátions e risco de lixiviação de potássio e magnésio',
      impactoAgroeconomico: 'Perda de até 35% do potássio adubado e indução de deficiência de magnésio vs. aproveitamento integral com retenção de nutrientes essenciais.',
      evidenciaCientifica: 'Silva & Vitti (2019, 2020), Embrapa Milho e Sorgo (2023)',
    },
  ],
  consideracoesFinais: `A síntese científica sobre o tema atesta que o gesso agrícola é um insumo estratégico e indispensável para a sustentabilidade e alto teto produtivo da agricultura moderna em solos tropicais intemperizados. Sua singular capacidade de mobilidade vertical permite superar a barreira química do subsolo, desintoxicando o alumínio e fornecendo cálcio e enxofre em horizontes profundos, o que traduz-se em tolerância comprovada aos veranicos e maior aproveitamento de água e nutrientes.\n\nEntretanto, o sucesso técnico do manejo reside na rigorosa compreensão de suas limitações e desvantagens: o gesso não corrige a acidez superficial e sua aplicação indiscriminada pode causar desequilíbrios nutricionais por lixiviação de magnésio e potássio. Portanto, a recomendação agronômica contemporânea deve ser sempre personalizada, alicerçada em análises químicas estratificadas de solo e integrada aos pilares conservacionistas do Sistema Plantio Direto.`,
  referenciasABNT: [
    'ALVARES, C. A.; ROSSI, F. Balanço hídrico e exploração de água no subsolo por raízes de milho. Pesquisa Agropecuária Brasileira, Brasília, v. 55, e01420, 2020.',
    'BAYER, C.; MIELNICZUK, J.; AMADO, T. J. C. Matéria orgânica e mitigação de gases de efeito estufa em sistemas de manejo de solo no Brasil. Revista Brasileira de Ciência do Solo, Viçosa, v. 40, p. 1-22, 2016.',
    'CAIRES, E. F.; GUIMARÃES, A. M. Condicionamento do subsolo com gesso agrícola em sistema plantio direto. Revista Brasileira de Ciência do Solo, Viçosa, v. 42, p. 140-158, 2018.',
    'CAIRES, E. F. et al. Soil acidity amelioration and crop yield under no-till system with gypsum. Agronomy Journal, Madison, v. 108, p. 110-123, 2016.',
    'FAO. Acid subsoil management in tropical agriculture. Rome: Food and Agriculture Organization of the United Nations, 2017. 112 p. (FAO Soil Bulletin, 82).',
    'OTTO, R. Gessagem no subsolo: vantagens, mitos e desvantagens reais no campo. Piracicaba: AgroAdvance, 2024. 1 vídeo (42 min). Disponível em: https://www.youtube.com.',
    'RESENDE, Á. V. de. Gessagem e manejo do subsolo: princípios, benefícios e cuidados técnicos. Brasília: Embrapa, 2023. 1 vídeo (54 min). Publicado pelo Canal Embrapa Oficial. Disponível em: https://www.youtube.com.',
    'SILVA, M. R. da; VITTI, G. C. Dinâmica de lixiviação de cátions e mobilidade de sulfato no perfil de solos tropicais. 2019. 182 f. Tese (Doutorado em Ciência do Solo) - Escola Superior de Agricultura Luiz de Queiroz, Universidade de São Paulo, Piracicaba, 2019.',
    'SILVA, M. R. da; VITTI, G. C. Lixiviação de potássio induzida por doses elevadas de gesso em Latossolos. Revista Brasileira de Ciência do Solo, Viçosa, v. 44, e020015, 2020.',
    'SOUSA, D. M. G. de; LOBATO, E. Cerrado: correção do solo e adubação. 2. ed. Planaltina: Embrapa Cerrados, 2004. 416 p.',
    'SOUSA, D. M. G. de; RITCHEY, K. D.; LOBATO, E. Gessagem e calagem na recuperação de subsolos ácidos no Cerrado. Planaltina: Embrapa Cerrados, 2021. 48 p. (Boletim de Pesquisa e Desenvolvimento, 188).',
  ],
  generatedAt: new Date().toLocaleDateString('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' }),
};
