export type TractorSymbol = {
  id: string;
  title: string;
  iso: string;
  meaning: string;
  application: string;
  imageUrl: string;
  sourceUrl: string;
  sourceLabel: string;
};

const commons = (ref: string) => `https://commons.wikimedia.org/wiki/Special:FilePath/ISO_7000_-_Ref-No_${ref}.svg`;
const commonsPage = (ref: string) => `https://commons.wikimedia.org/wiki/File:ISO_7000_-_Ref-No_${ref}.svg`;

export const TRACTOR_SYMBOLS: TractorSymbol[] = [
  {id:'engine',title:'Motor de combustão interna',iso:'ISO 7000-1156',meaning:'Identifica o motor, especialmente motor alternativo de combustão interna.',application:'Usado em comandos, indicadores e documentação relacionados ao motor.',imageUrl:commons('1156'),sourceUrl:commonsPage('1156'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'transmission',title:'Transmissão',iso:'ISO 7000-1166',meaning:'Identifica a transmissão do veículo/máquina.',application:'Relaciona-se ao conjunto de transmissão e seus controles/indicadores.',imageUrl:commons('1166'),sourceUrl:commonsPage('1166'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'hydraulic',title:'Sistema hidráulico',iso:'ISO 7000-1409',meaning:'Identifica o sistema hidráulico.',application:'Usado para reconhecer o circuito hidráulico e seus controles/indicadores.',imageUrl:commons('1409'),sourceUrl:commonsPage('1409'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'oil',title:'Óleo',iso:'ISO 7000-1056',meaning:'Identifica óleo e funções relacionadas à lubrificação.',application:'Pode aparecer em indicadores e pontos de serviço do sistema de lubrificação.',imageUrl:commons('1056'),sourceUrl:commonsPage('1056'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'coolant',title:'Líquido de arrefecimento',iso:'ISO 7000-0536',meaning:'Identifica líquido de arrefecimento/água.',application:'Relaciona-se ao sistema de arrefecimento do motor.',imageUrl:commons('0536'),sourceUrl:commonsPage('0536'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'brake',title:'Sistema de freio',iso:'ISO 7000-1399',meaning:'Identifica o sistema de freio.',application:'Usado em controles e indicadores associados ao sistema de frenagem.',imageUrl:commons('1399'),sourceUrl:commonsPage('1399'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'rockshaft',title:'Braços de levante / rockshaft',iso:'ISO 7000-1566',meaning:'Identifica o comando ou o estado do levante traseiro (rockshaft).',application:'Indica o sistema que eleva ou abaixa o implemento acoplado.',imageUrl:commons('1566'),sourceUrl:commonsPage('1566'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'rockshaft-up',title:'Levante — subir',iso:'ISO 7000-1567',meaning:'Indica o movimento de elevação do rockshaft.',application:'Identifica a direção/comando de subida do implemento.',imageUrl:commons('1567'),sourceUrl:commonsPage('1567'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'rockshaft-down',title:'Levante — baixar',iso:'ISO 7000-1568',meaning:'Indica o movimento de descida do rockshaft.',application:'Identifica a direção/comando de descida do implemento.',imageUrl:commons('1568'),sourceUrl:commonsPage('1568'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'remote-cylinder',title:'Cilindro hidráulico remoto',iso:'ISO 7000-1569',meaning:'Identifica um cilindro hidráulico remoto.',application:'Usado para reconhecer funções hidráulicas remotas.',imageUrl:commons('1569'),sourceUrl:commonsPage('1569'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'remote-extend',title:'Cilindro remoto — estender',iso:'ISO 7000-1570',meaning:'Indica a extensão do cilindro hidráulico remoto.',application:'Identifica a direção de acionamento correspondente à extensão.',imageUrl:commons('1570'),sourceUrl:commonsPage('1570'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'remote-retract',title:'Cilindro remoto — retrair',iso:'ISO 7000-1571',meaning:'Indica a retração do cilindro hidráulico remoto.',application:'Identifica a direção de acionamento correspondente à retração.',imageUrl:commons('1571'),sourceUrl:commonsPage('1571'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'diff-lock',title:'Bloqueio do diferencial',iso:'ISO 7000-1662',meaning:'Identifica o comando/estado do bloqueio do diferencial.',application:'Indica a função que força as rodas de um eixo a girarem em conjunto, conforme o sistema.',imageUrl:commons('1662'),sourceUrl:commonsPage('1662'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'front-drive',title:'Tração dianteira auxiliar',iso:'ISO 7000-1663',meaning:'Identifica o acionamento da tração dianteira auxiliar.',application:'Usado para o comando/estado do sistema de tração dianteira do trator.',imageUrl:commons('1663'),sourceUrl:commonsPage('1663'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'pto',title:'Tomada de potência (TDP/PTO)',iso:'ISO 7000-1572',meaning:'Identifica o sistema de tomada de potência.',application:'Usado para o comando e indicação de estado da TDP/PTO.',imageUrl:commons('1572'),sourceUrl:commonsPage('1572'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'pto-cw',title:'TDP — sentido horário',iso:'ISO 7000-1664',meaning:'Indica rotação horária da tomada de potência, observada da frente da extremidade do eixo.',application:'Usado para identificar o sentido de rotação indicado para a TDP.',imageUrl:commons('1664'),sourceUrl:commonsPage('1664'),sourceLabel:'ISO 3767-2 / ISO 7000'},
  {id:'wheel-slip',title:'Patinagem das rodas',iso:'ISO 7000-1665',meaning:'Indica o grau de patinagem das rodas.',application:'Relaciona a diferença entre velocidade real de avanço e velocidade implícita pela rotação das rodas motrizes.',imageUrl:commons('1665'),sourceUrl:commonsPage('1665'),sourceLabel:'ISO 3767-2 / ISO 7000 — SVG CC0'},
  {id:'position-lights',title:'Luzes de posição',iso:'ISO 7000-0456',meaning:'Identifica as luzes de posição/laterais.',application:'Usado para comando ou indicação das luzes de baixa intensidade de posição.',imageUrl:commons('0456'),sourceUrl:commonsPage('0456'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'parking-brake',title:'Freio de estacionamento',iso:'ISO 7000-0238',meaning:'Identifica o freio de estacionamento e, conforme a aplicação, sua condição de falha.',application:'Indicador relacionado ao freio de estacionamento; a cor e a lógica do painel dependem da aplicação.',imageUrl:commons('0238'),sourceUrl:commonsPage('0238'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'parking-lights',title:'Luzes de estacionamento',iso:'ISO 7000-0240',meaning:'Identifica o comando/estado das luzes de estacionamento.',application:'Usado para reconhecer a função de iluminação de baixa intensidade de estacionamento.',imageUrl:commons('0240'),sourceUrl:commonsPage('0240'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'tractor-side',title:'Trator — vista lateral',iso:'ISO 7000-2133',meaning:'Representa um trator em vista lateral.',application:'É usado como elemento gráfico para identificar o trator em determinadas funções e símbolos combinados.',imageUrl:commons('2133'),sourceUrl:commonsPage('2133'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'tractor-top',title:'Trator — vista superior',iso:'ISO 7000-2134',meaning:'Representa um trator em vista superior/planta.',application:'Usado para identificar o trator em vista de cima e em símbolos combinados.',imageUrl:commons('2134'),sourceUrl:commonsPage('2134'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'slip-axle',title:'Bloqueio do diferencial de eixo',iso:'ISO 7000-2599',meaning:'Identifica o bloqueio do diferencial de um eixo motriz.',application:'Indicador/comando associado ao sistema diferencial do eixo.',imageUrl:commons('2599'),sourceUrl:commonsPage('2599'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'inter-axle-lock',title:'Bloqueio entre eixos',iso:'ISO 7000-2600',meaning:'Identifica o bloqueio entre eixos.',application:'Usado em sistemas que possuem função de bloqueio entre eixos.',imageUrl:commons('2600'),sourceUrl:commonsPage('2600'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'hood-open',title:'Capô do trator — abrir',iso:'ISO 7000-3694',meaning:'Identifica o comando que libera/abre o capô do trator ou indica que ele está aberto.',application:'Relaciona-se ao acesso ao compartimento do motor.',imageUrl:commons('3694'),sourceUrl:commonsPage('3694'),sourceLabel:'ISO 7000 / Wikimedia Commons — SVG CC0'},
  {id:'pto-stop',title:'TDP — parada',iso:'ISO 7000-3692',meaning:'Identifica o comando que interrompe toda a potência da TDP e indica que ela está parada.',application:'Função de parada da TDP prevista na atualização da ISO 3767-2.',imageUrl:commons('3692'),sourceUrl:commonsPage('3692'),sourceLabel:'ISO 3767-2:2016/Amd.1:2020 / ISO 7000 — SVG CC0'},
];
