'use client';

import { ReferenceTypeConfig } from './types';

export const ABNT_MONTHS: Record<string, string> = {
  '01': 'jan.',
  '02': 'fev.',
  '03': 'mar.',
  '04': 'abr.',
  '05': 'mai.',
  '06': 'jun.',
  '07': 'jul.',
  '08': 'ago.',
  '09': 'set.',
  '10': 'out.',
  '11': 'nov.',
  '12': 'dez.',
  janeiro: 'jan.',
  fevereiro: 'fev.',
  março: 'mar.',
  abril: 'abr.',
  maio: 'mai.',
  junho: 'jun.',
  julho: 'jul.',
  agosto: 'ago.',
  setembro: 'set.',
  outubro: 'out.',
  novembro: 'nov.',
  dezembro: 'dez.',
  jan: 'jan.',
  fev: 'fev.',
  mar: 'mar.',
  abr: 'abr.',
  mai: 'mai.',
  jun: 'jun.',
  jul: 'jul.',
  ago: 'ago.',
  set: 'set.',
  out: 'out.',
  nov: 'nov.',
  dez: 'dez.',
};

export const DOI_REGEX = /^10\.\d{4,9}\/[-._;()\/:A-Z0-9]+$/i;
export const URL_REGEX = /^https?:\/\/.+/;

export const REFERENCE_TYPES: ReferenceTypeConfig[] = [
  {
    id: 'book',
    label: 'Livro',
    description: 'Livro ou folheto impresso',
    icon: 'BookOpen',
    requiredFields: ['authors', 'title', 'location', 'publisher', 'year'],
    optionalFields: ['subtitle', 'edition', 'pagesTotal', 'series', 'isbn', 'notes'],
  },
  {
    id: 'book_chapter',
    label: 'Capítulo de Livro',
    description: 'Capítulo ou seção de livro',
    icon: 'BookMarked',
    requiredFields: ['authors', 'title', 'bookAuthor', 'bookTitle', 'location', 'publisher', 'year', 'pages'],
    optionalFields: ['subtitle', 'edition'],
  },
  {
    id: 'book_electronic',
    label: 'Livro Eletrônico',
    description: 'E-book ou livro digital',
    icon: 'Laptop',
    requiredFields: ['authors', 'title', 'location', 'publisher', 'year'],
    optionalFields: ['subtitle', 'edition', 'url', 'accessDate', 'isbn'],
  },
  {
    id: 'journal_article',
    label: 'Artigo de Periódico',
    description: 'Artigo em revista científica impressa',
    icon: 'FileText',
    requiredFields: ['authors', 'title', 'journalTitle', 'location', 'volume', 'number', 'pages', 'year'],
    optionalFields: ['subtitle', 'month', 'tomo'],
  },
  {
    id: 'journal_article_online',
    label: 'Artigo de Periódico Online',
    description: 'Artigo em revista científica digital',
    icon: 'FileText',
    requiredFields: ['authors', 'title', 'journalTitle', 'year'],
    optionalFields: ['subtitle', 'location', 'volume', 'number', 'pages', 'month', 'tomo', 'doi', 'url', 'accessDate'],
  },
  {
    id: 'newspaper_article',
    label: 'Artigo de Jornal',
    description: 'Matéria em jornal impresso',
    icon: 'Newspaper',
    requiredFields: ['authors', 'title', 'journalTitle', 'location', 'date', 'pages'],
    optionalFields: ['subtitle', 'section'],
  },
  {
    id: 'newspaper_article_online',
    label: 'Artigo de Jornal Online',
    description: 'Matéria em jornal digital',
    icon: 'Newspaper',
    requiredFields: ['authors', 'title', 'journalTitle', 'date'],
    optionalFields: ['subtitle', 'location', 'section', 'url', 'accessDate'],
  },
  {
    id: 'website',
    label: 'Site / Documento Online',
    description: 'Página web ou portal',
    icon: 'Globe',
    requiredFields: ['title', 'url', 'accessDate'],
    optionalFields: ['authors', 'subtitle', 'organization', 'year', 'description'],
  },
  {
    id: 'thesis',
    label: 'Tese / Dissertação / TCC',
    description: 'Trabalho acadêmico',
    icon: 'GraduationCap',
    requiredFields: ['authors', 'title', 'degree', 'institution', 'location', 'year'],
    optionalFields: ['subtitle', 'advisor'],
  },
  {
    id: 'conference',
    label: 'Trabalho de Evento',
    description: 'Artigo ou trabalho de congresso/conferência',
    icon: 'CalendarDays',
    requiredFields: ['authors', 'title', 'eventName', 'eventLocation', 'eventYear', 'bookTitle', 'location', 'publisher', 'year', 'pages'],
    optionalFields: ['subtitle', 'eventNumber'],
  },
  {
    id: 'technical_standard',
    label: 'Norma Técnica',
    description: 'Norma ABNT ou similar',
    icon: 'FileCheck',
    requiredFields: ['standardOrganization', 'title', 'standardNumber', 'location', 'year'],
    optionalFields: ['standardYear'],
  },
  {
    id: 'legislation',
    label: 'Legislação',
    description: 'Lei, decreto, portaria etc.',
    icon: 'Scale',
    requiredFields: ['legislationType', 'legislationNumber', 'legislationYear', 'legislationSource', 'legislationDate'],
    optionalFields: ['legislationEmenta'],
  },
  {
    id: 'patent',
    label: 'Patente',
    description: 'Documento de patente',
    icon: 'Shield',
    requiredFields: ['inventor', 'title', 'patentNumber', 'filingDate', 'grantDate'],
    optionalFields: ['location'],
  },
  {
    id: 'audiovisual',
    label: 'Documento Audiovisual',
    description: 'Vídeo, podcast, áudio',
    icon: 'Film',
    requiredFields: ['authors', 'title', 'audiovisualType', 'year'],
    optionalFields: ['platform', 'url', 'accessDate', 'duration', 'description'],
  },
  {
    id: 'ai_tool',
    label: 'Ferramenta de IA',
    description: 'ChatGPT, Gemini etc.',
    icon: 'Brain',
    requiredFields: ['organization', 'title', 'aiVersion', 'aiLocation', 'year', 'url', 'accessDate'],
    optionalFields: ['aiModel', 'description'],
  },
];
